name: checker
on: [push, pull_request]
jobs:
  googletest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-build # キャッシュしたいかも
        shell: bash
        run: make dc-build
      - name: compose up
        shell: bash
        run: make dc-up
      - name: cpplint
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yml exec -T webserv make lint
      - name: clang-tidy
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yml exec -T webserv make tidy
      - name: 単体テスト
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yml exec -T webserv make utest
      - name: 結合テスト
        shell: bash
        run: make itest
