name: checker
on:
  push:
    branches:
      - main
  pull_request:
    paths-ignore:
      - "docs/**"
      - "sample_data"
      - "README.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
      - name: Build images
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          tags: webserv
          load: true
          context: ./docker/webserv
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

  program_check:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ github.ref }}-${{ github.sha }}
      - name: Build images
        uses: docker/build-push-action@v2
        with:
          push: false
          builder: ${{ steps.buildx.outputs.name }}
          tags: webserv
          load: true
          context: ./docker/webserv
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
      - name: compose-build # キャッシュしたいかも
        shell: bash
        run: DOCKER_BUILDKIT=1 COMPOSE_DOCKER_CLI_BUILD=1 make dc-build
      - name: compose up
        shell: bash
        run: make dc-up
      - name: clang-format
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yml exec -T webserv make format
      - name: make
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yml exec -T webserv make re
      - name: cpplint
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yml exec -T webserv make lint
      - name: clang-tidy
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yml exec -T webserv make tidy
      - name: 単体テスト
        shell: bash
        run: docker compose -f ./docker/webserv/docker-compose.yml exec -T webserv make utest
      - name: 結合テスト
        shell: bash
        run: make itest
