# GitHub Action to run cpplint recursively on all pushes and pull requests
# https://github.com/cpplint/GitHub-Action-for-cpplint

name: googletest
on: [push, pull_request]
jobs:
  googletest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: curl -OL https://github.com/google/googletest/archive/release-1.10.0.tar.gz
      - run: tar -zxvf release-1.10.0.tar.gz
      - run: mkdir -p googletest-release-1.10.0/build && cd googletest-release-1.10.0/build && cmake .. && make install
      - run: make test
