name: googletest
on: [push, pull_request]
jobs:
  googletest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-build
        shell: bash
        run: docker-compose build webserv
      - name: run google test
        shell: bash
        run: docker-compose up -d
      - name: run google test
        shell: bash
        run: docker-compose exec -T webserv make test
