name: valgrind
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  valgrind:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: compose-build
        shell: bash
        run: make dc-build
      - name: valgrind
        shell: bash
        run: make valgrind
      - name: summary log
        shell: bash
        run: cat ./log/summary-valgrind.log
